brum08-cv05
nvbach91/4IZ278-2020-2021-LS pull request #138
Opened 2021-03-22 00:52 UTC by wellsinik

Z nějakého důvodu mi nefunguje VPN a nemohu to nahrát na server, zkusím to zítra během dopoledne.
https://eso.vse.cz/~brum08/cv05/

2021-03-22 01:11 UTC, wellsinik commented
Nakonec se mi to podařilo, ale na serveru to nefunguje, nemůže to najít cestu s jednotlivým databázím
Výstup na localu:
![image](https://user-images.githubusercontent.com/49476222/111928418-d444f480-8ab3-11eb-8440-d817e52d3022.png)
![image](https://user-images.githubusercontent.com/49476222/111928435-ddce5c80-8ab3-11eb-8863-df8d756028f7.png)

2021-03-25 13:02 UTC, nvbach91 commented
mate vsude spatne zretezenou cestu ke souborum, to vidite z warningu

![image](https://user-images.githubusercontent.com/20724910/112476876-a8a36200-8d72-11eb-82a8-de8ee858fd22.png)

2021-03-25 13:02 UTC, nvbach91 requested changes

2021-03-25 13:02 UTC, nvbach91 commented on www/brum08/cv05/database.php
> +            $file = file($this->dbPath.'Orders'.$this->dbExtension);
napriklad tady, a na vsech mistech

2021-03-29 10:26 UTC, wellsinik commented
Opraveno, cesta je již správně

2021-04-08 07:19 UTC, nvbach91 approved these changes
Jeste byste mel nastavit pravo na zapis do souboru pro PHP, viz navod v zadani

2021-04-08 07:20 UTC, merged