Vrbj04 cv06
nvbach91/4IZ278-2020-2021-LS pull request #144
Opened 2021-03-26 11:36 UTC by jirkavrba

Z nějakého důvodu mi na ESO nefunguje načítání dat z databáze, připojení ani nic jiného nevyhodí výjimku, ale přesto, že v databázi jsou data, vrací mi PDO prázdnou množinu.

Connection string jsem samozřejmě vymněnil, připojuji se ve tvaru `vrbj04:heslo@localhost`, použil jsem heslo ze souboru na eso.

![image](https://user-images.githubusercontent.com/14146321/112625957-dbf7f680-8e2f-11eb-9fbe-303eb48e81c0.png)

2021-03-26 11:36 UTC, jirkavrba commented
Adresa je tedy `https://eso.vse.cz/~vrbj04/cv06/`

2021-03-26 11:44 UTC, nvbach91 requested changes

2021-03-26 11:44 UTC, nvbach91 commented on www/vrbj04/cv06/index.php
> +$connection = new PDO("mysql:host=localhost;port=3306;dbname=weby;user=weby;password=password");
```php
PDO("
mysql:host=localhost;
dbname=weby;
username=weby;            // <- ze by toto?
password=password
")
```

2021-03-26 11:45 UTC, jirkavrba commented on www/vrbj04/cv06/index.php
> +$connection = new PDO("mysql:host=localhost;port=3306;dbname=weby;user=weby;password=password");
Vyzkouším

2021-03-26 11:46 UTC, jirkavrba commented on www/vrbj04/cv06/index.php
> +$connection = new PDO("mysql:host=localhost;port=3306;dbname=weby;user=weby;password=password");
Změnil jsem na username a stále nic...
![image](https://user-images.githubusercontent.com/14146321/112626975-45c4d000-8e31-11eb-93e3-de9db651b292.png)

2021-03-26 12:25 UTC, mart10vse commented on www/vrbj04/cv06/index.php
> +$connection = new PDO("mysql:host=localhost;port=3306;dbname=weby;user=weby;password=password");
dbname je taky vrbj04 jestli vidím dobře

2021-03-26 13:31 UTC, nvbach91 commented on www/vrbj04/cv06/index.php
> +$connection = new PDO("mysql:host=localhost;port=3306;dbname=weby;user=weby;password=password");
na serveru eso mate pouze jednu databazi pojmenovanou vasim xnamem. v kodu ted mate dbname=test

2021-04-08 07:24 UTC, nvbach91 approved these changes

2021-04-08 07:24 UTC, merged