blak05-cv09
nvbach91/4IZ278-2020-2021-LS pull request #214
Opened 2021-04-18 17:59 UTC by krystofblak05

https://eso.vse.cz/~blak05/cv09/index.php

2021-04-21 13:23 UTC, krystofblak05 commented
Vidím, že kolegové sem přidali i údaje pro admin účet - mail: admin@vse.cz, heslo: admin

2021-04-21 23:43 UTC, nvbach91 requested changes

2021-04-21 23:43 UTC, nvbach91 commented on www/blak05/cv09/auth2.php
> +echo $number;
zakomentovat

2021-04-21 23:43 UTC, nvbach91 commented on www/blak05/cv09/users.php
> +        <input name="privilege" class="form-control" type="privilege" value="<?php echo $user['privilege']?>">
chtelo by to vytvorit select - z jakych moznych opravneni lze vybrat, nenechat jako volny text

2021-04-23 08:13 UTC, nvbach91 approved these changes

2021-04-23 08:14 UTC, merged