Student tson00
nvbach91/4IZ278-2020-2021-LS pull request #22
Opened 2021-02-19 13:47 UTC by tson00

cv01

2021-02-19 13:50 UTC, nvbach91 requested changes

2021-02-19 13:50 UTC, nvbach91 commented on www/tson00/cv01/index.php
> +    <table>
nedoporucuji to delat do `<table>`

2021-02-19 13:50 UTC, nvbach91 commented on www/tson00/cv01/index.php
> +        </tbody>
chce to naformatovat

2021-02-19 13:50 UTC, nvbach91 commented on www/tson00/cv01/index.php
> +<style>
tohle sem nepatri

2021-02-19 17:21 UTC, tson00 commented on www/tson00/cv01/index.php
> +<style>
hodila jsem to do hlavicky

2021-02-19 17:21 UTC, tson00 commented on www/tson00/cv01/index.php
> +    <table>
je to v <div></div>

2021-02-19 17:22 UTC, tson00 commented on www/tson00/cv01/index.php
> +        </tbody>
snad takhle staci

2021-02-20 12:39 UTC, nvbach91 requested changes

2021-02-20 12:39 UTC, nvbach91 commented on www/tson00/cv01/index.php
> +      <p style="float: left;"><img src="<?php echo $avatar;?>" height="320px" width="390px" border="1px"></p>
kam zmizel atribut alt? jinak tohle je nevalidni HTML a navic CSS pravidla nepiseme do atributu style, ani do tagy styles, ale do samostatneho souboru

2021-02-22 09:39 UTC, nvbach91 approved these changes

2021-02-22 09:39 UTC, merged