vrbj04 semestralni prace
nvbach91/4IZ278-2020-2021-LS pull request #225
Opened 2021-04-24 10:56 UTC by jirkavrba

Momentálně je dostupné online na adrese https://semestralni-prace-4iz278.herokuapp.com/ (první načtení po delší době může trvat trochu déle, protože musí nabootovat container)

2021-06-03 16:17 UTC, nvbach91 requested changes
- favorite collections -> favorite cards
- k cemu je ten external link?
- chybi odkaz z practice zpatky na flashcard
- po editaci question dostavam 404

2021-06-03 16:56 UTC, jirkavrba commented
Co se myslí tím **favorite collections -> favorite cards**?
+ nedaří se mi zreplikovat tu 404, na localhostu i na deploynuté verzi mi to funguje správně :man_shrugging:

2021-06-03 17:03 UTC, nvbach91 commented
- kdyz si pridam kartu do favorites tak se mi zobrazi na domovske strance, pod nadpisem favorite collections, ma to byt favorite cards
- viz video 

https://user-images.githubusercontent.com/20724910/120683820-5bdcb580-c49e-11eb-84f7-e97ac43cb682.mp4


- co se stane kdyz zadam do URL id kolekce ktera je private a neni moje?

2021-06-03 17:08 UTC, jirkavrba commented
Zobrazení privátních kolekcí je podmíněné autorizací v rámci Policy,  v takovém případě se vrátí 403 Forbidden chyba

2021-06-03 17:23 UTC, jirkavrba commented
Měla by být deploynutá opravená verze

2021-06-04 08:32 UTC, nvbach91 approved these changes

2021-06-04 08:33 UTC, merged