sp-akod00
nvbach91/4IZ278-2020-2021-LS pull request #233
Opened 2021-05-07 09:32 UTC by hailstorm75

http://meetnow-thesis.herokuapp.com/dashboard

2021-06-03 15:55 UTC, nvbach91 requested changes
- po kliknuti na tlacitko create se mi neprida zadny event
- take nevidim zadne dostupne eventy k vyzkouseni

2021-06-03 17:20 UTC, hailstorm75 commented
Chyba s nezobrazenim vytvorene udalosti byla opravena. Zadne hotove udalosti v aplikaci nejsou, jelikoz jsem predpokladal spolecne vyzkouseni az na obhajobe.

2021-06-03 17:29 UTC, hailstorm75 commented
Pro vyzkouseni Join, lze vyuzit nasledujici kod: 179d2aa3-3b6f-4000-8404-606f168799d0

2021-06-04 08:32 UTC, nvbach91 approved these changes

2021-06-04 08:32 UTC, merged