Prvotní verze po dokončení 1. AJAX gadgetu.
nvbach91/4IZ278-2020-2021-LS pull request #236
Opened 2021-05-08 22:46 UTC by 637man

To jest převodník mezi různými písmy (scripts, nikoliv fonts). Jazyk je totiž možné psát nejen v latince.

2021-05-16 21:31 UTC, nvbach91 requested changes
chtelo by vymyslet nejakou strukturu podslozek

2021-06-22 23:56 UTC, 637man commented
Struktura adresářů vymyšlena. Zabřednutí do studia historických písem pro převodník. ᛋᛟᚱᛖ ᚨᛚ ᚨᚴᛒᚨᚱ ᚹᚨᛗᚨᛃ, ᚨᚾᚨ ᛁᛗᚨ ᚾᛁ ᚴᚨᛏᚨᛒᚨ. (To je nejlepší hračka, kterou jsem kdy napsal.) Nástřel vyhledávání, jež bude základem anotace spatlané jako obvykle poslední noc. Stále chybí dopsat databázové pohledy složitostí se podobající Thesauru. Pushnuto kvůli tomu, že to má být 48h před obhajobou.

2021-06-24 08:21 UTC, nvbach91 requested changes
- uplne chybi navigace, jak mam prechazet mezi strankami?
- HTML neni validni nikde
- insertDictEntry - odeslani formulare vyvolava undefined variable
- insertThesaurus - odeslani formulare vyvolava undefined variable
- insertIdiom - odeslani formulare vyvolava undefined variable, undefined index
- insertDeriv - odeslani formulare vyvolava PDO exception 

![image](https://user-images.githubusercontent.com/20724910/123225669-3a864c80-d4d3-11eb-9cd1-0c9df3577ee5.png)

- viewIdiom, viewDictEntry- prazdne stranky, Test na slovíčka a Test z aritmetiky a logiky nikam nevedou
- scriptConverter - jestli chcete pouzivat AJAX tak server by mel vratit JSON a ne HTML
- search.php vubec nefunguje, searchServer.php vraci 404
- to ze se zavola XHR request na kazdem zmacknuti klavesy je spatne, mel by se pouzivat tzv. debounce

- validace vstupu nic moc
- OOP nikde
- nemate prihlaseni/registrace? autentizace, autorizace, OAuth?
- pouzivate nekde optimistic/pessimistic lock?
- cookie/session nikde
- knihovny nic
- (CR)UD nic
- SEO url nic
- Email nic

2021-06-24 08:21 UTC, nvbach91 commented on www/getj00/sp/db/insertDeriv.php
> +        $tvar=htmlspecialchars($_POST['tvar']);
prosim naformatovat kod, vsude

2021-06-24 08:21 UTC, nvbach91 commented on www/getj00/sp/db/insertDeriv.php
> +            $insertDeriv = $pdo->prepare("INSERT INTO Odvozenina (tvar, jazyk, vyznam, souhlasky, souprava) VALUES (:tvar, :jazodv, :vyz, :souhl, :soup);");
sql operace zapouzdrit do metody ve tride

2021-06-24 08:21 UTC, nvbach91 commented on www/getj00/sp/db/insertDeriv.php
> +                echo "<option value=\"$langCodes[$i]\">$langCodes[$i] - $langNames[$i]</option>";
HTML nedavame do echo, pouze promenne

2021-06-25 00:48 UTC, 637man commented
> * uplne chybi navigace, jak mam prechazet mezi strankami?
Tlačítkem Zpět v prohlížeči, Alt+Backspace, nebo otevíráním odkazů v nových záložkách. Do patičky přidán odkaz zpět na hlavní menu. Víc než 1 úroveň hluboko struktura stránky nesahá.

> * HTML neni validni nikde
Chromium si nestěžuje, důležité je pro mě, co funguje. Soulad se specifikací budu řešit tehdy, až nebudu muset dodělávat věci na poslední chvíli a přepínat mezi několika předměty.

> * insertDictEntry - odeslani formulare vyvolava undefined variable
> * insertThesaurus - odeslani formulare vyvolava undefined variable
> * insertIdiom - odeslani formulare vyvolava undefined variable, undefined index
> * insertDeriv - odeslani formulare vyvolava PDO exception
Opraveno jen částečně, ESO vypovědělo funkčnost (prázdné odpovědi). Migrace na domácí Synology vyžaduje rekonfigurovat připojení k DB.

> * viewIdiom, viewDictEntry- prazdne stranky, Test na slovíčka a Test z aritmetiky a logiky nikam nevedou
Přidány pahýly pro viewDictEntry a viewIdiom, testy na slovíčka ani na aritmetiku jsou stále jen plánované vlastnosti.

> * scriptConverter - jestli chcete pouzivat AJAX tak server by mel vratit JSON a ne HTML
> * to ze se zavola XHR request na kazdem zmacknuti klavesy je spatne, mel by se pouzivat tzv. debounce
Přidán kód pro generování JSON (méně čitelné než tabulka, ale budiž) a pokus o debounce, ale porušil jsem zásadu funguje to - nešťourej do toho, a teď to nejspíš nefunguje.

> * search.php vubec nefunguje, searchServer.php vraci 404
To nebylo dodělané, a není ani teď, ale alespoň by to mělo něco z té DB získat.

> * validace vstupu nic moc
Z větší části ji dělá MySQL, proto ty exceptions. Kdyby umělo dobře PL/SQL, nedělal bych na aplikační úrovni validaci žádnou.

> * OOP nikde
> * knihovny nic
Díky absenci knihoven netrvá několik sekund, než se načtou všechny ty kontejnery či co. Zatím jsem nenašel případ, kdy by mi OOP nějak výrazně pomohlo, vždy mě jenom omezovalo, a několik projektů dokonce zkazilo. Mimoto se nejedná o tak složitý portál. Nikdy víc.

> * nemate prihlaseni/registrace? autentizace, autorizace, OAuth?
> * cookie/session nikde
> * Email nic
> * SEO url nic
Tenhle portál bude mít reálně 2 pravidelné uživatele, a 1 z nich jsem já. Mimoto zatím nebyly implementovány žádné vlastnosti, které by uživatelské účty nějak využily. Rád bych vedl nějaké hi-score žebříčky v navržených kořenech a testech, ale to bych je nejdřív musel naimplementovat. Rozesílání e-mailů je sice hezké, ale spamu už lítá po SMTP dost, pročež je na školní síti firewall.

> * (CR)UD nic
> * pouzivate nekde optimistic/pessimistic lock?
S databází lze přes web provádět Create a Read. Update a Delete má dělat správce (já), aby opravil chyby v datech a učinil finální rozhodnutí o obsahu. Zamykání záznamů jsem se tedy vhodným návrhem vyhnul.

2021-06-25 13:59 UTC, nvbach91 approved these changes

2021-06-25 13:59 UTC, merged