zjaa00-cv01
nvbach91/4IZ278-2020-2021-LS pull request #24
Opened 2021-02-19 14:21 UTC by socka25

Odovzdávam cvičenie 01. Ospravedlňujem sa, že to tu posielam až teraz, ale nevšimol som si pozvánku na emaile, ktorá mi dáva práva sem uploadovať.

2021-02-19 14:29 UTC, nvbach91 requested changes
vyhodte z pull requestu ty nepotrebne soubory

2021-02-19 17:47 UTC, socka25 commented
> vyhodte z pull requestu ty nepotrebne soubory

Máte na mysli iba webfonty, ktoré som nevyužil pri tvorbe stránky alebo mám vyhodiť všetky súbory, ktoré som buď nepísal sám (súbory zabezpečujúce kompatibilitu) alebo neobsahujú kód resp. všetky okrem `header.php`, `index.php`, `footer.php` a `style.css`?

2021-02-20 12:43 UTC, nvbach91 commented
Ano, myslim ty webfonty, jinak pro priste uprednosnujte import z CDN, napr ten normalize muzete importovat takto:
- https://cdnjs.com/libraries/normalize

2021-02-20 12:43 UTC, nvbach91 approved these changes

2021-02-20 12:43 UTC, merged