vonm10-SP
nvbach91/4IZ278-2020-2021-LS pull request #248
Opened 2021-05-15 13:09 UTC by vonm10

2021-06-17 15:10 UTC, nvbach91 commented
jaky je odkaz na vasi aplikaci?

2021-06-17 15:23 UTC, vonm10 commented
@nvbach91 https://eso.vse.cz/~vonm10/beardwithme/index.php 

Pardon, zapomnel jsem vlozit

2021-06-17 15:49 UTC, nvbach91 requested changes
- pridejte footer
- opravte header
- seznam kategorii zobrazujte na vsech strankach produktu a zvyraznete aktivni kategorii
- zarovnejte produkty na stred
- k cemu jsou ty hvezdicky u produktu?
- proc nelze nakoupit uz pred registraci?
- pridejte moznost pridani produktu do kosiku uz pri zobrazeni kategorii i na hlavni strance v slideru
- opravte vzhled loginu, registrace
- opravte proces loginu
- pridejte moznost nakupu vice kusu
- v kosiku pridejte odkaz na produkt 
- jak vyberu moznost platby a dopravy?
- jak si zobrazim jiz zadane objednavky?


neni tam toho moc, obavam se, ze budete muse hodne dodelavat, zatim se nebudu divat do kodu

2021-06-17 20:24 UTC, vonm10 commented
@nvbach91

- pridejte footer - pridano
- opravte header - opraveno prazdne misto
- seznam kategorii zobrazujte na vsech strankach produktu a zvyraznete aktivni kategorii - zobrazuji nyni i u kategorii
- zarovnejte produkty na stred - snad
- k cemu jsou ty hvezdicky u produktu? - byly z templatu, odebral jsem je
- proc nelze nakoupit uz pred registraci? - upravil jsem, aby bylo mozne pridavat do kosiku pred prihlasenim. Pro checkout je ale nutne se prihlasit kvuli ukladani do databaze
- pridejte moznost pridani produktu do kosiku uz pri zobrazeni kategorii i na hlavni strance v slideru - pridal jsem pro kategorie. Slider je nyni odkaz na produkt
- opravte vzhled loginu, registrace - neprijde mi to zas tak zle :)
- opravte proces loginu - myslite ten error u facebooku?
- pridejte moznost nakupu vice kusu - toto asi do zitra nezvladam
- v kosiku pridejte odkaz na produkt - pridano
- jak vyberu moznost platby a dopravy? - pridano
- jak si zobrazim jiz zadane objednavky? - pro adminy je mozne zobrazit objednavky v sekci Admin. Uzivatelum chodi objednavky do mailu (samozrejme jen na vse.cz)

2021-06-18 10:12 UTC, vonm10 commented
Posledni commit:

- pridani die() pri presmerovani
- vetsi osetreni vstupu (napr. regex pro URL)
- parametrizace vsech SQL dotazu
- pred smazanim produktu kontrolni select
- uplne nova tabulka pro mazani produktu
- uplne nova stranka pro zobrazeni objednavek uzivatelem

2021-06-18 10:23 UTC, nvbach91 approved these changes

2021-06-18 10:24 UTC, merged