sp-kore07
nvbach91/4IZ278-2020-2021-LS pull request #250
Opened 2021-05-15 21:07 UTC by liberty-12

Odevzdavam pilotni verzi SP

2021-06-23 04:27 UTC, liberty-12 commented
Odkaz na aplikaci: https://eso.vse.cz/~kore07/idevice/
Práce je hotová, ale mám problém s phpMyAdmin na eso-serveru, napsala jsem Vám do chatu v MSTeams

2021-06-23 10:51 UTC, liberty-12 commented
Problém vyřešen

2021-06-24 08:34 UTC, nvbach91 requested changes
- HTML neni validni
- OAuth nefunguje, musite nastavit Live mode
- vyhledavani nefunguje
- filter/zareni nefunguje
- kategorie nefunguje
- prosim vyhodte vsechny nefunkcni odkazy a tlacitka
- po update profilu dostavam `UPDATE users SET user_name = 'Nguyen Viet Bach', user_email = 'nguv03@vse.cz', user_address = 'a', user_zip = 'b', user_city = 'd', user_country = 'e', user_phone = '7' WHERE user_id = 7`
- chybi validace formulare na profile.php
- po odeslani objednavky jsem dostal stejny email jako po registraci
- po uspesne odeslani objednavky neni kosik vyprazdnen
- zcela chybi validace formulare objednavky

2021-06-25 13:39 UTC, nvbach91 approved these changes

2021-06-25 13:57 UTC, merged