sp-zjaa00
nvbach91/4IZ278-2020-2021-LS pull request #251
Opened 2021-05-16 12:12 UTC by socka25

Odovzdávam pilotnú verziu semestrálnej práce
odkaz na server eso je https://eso.vse.cz/~zjaa00/sp-zjaa00/

2021-05-20 08:03 UTC, socka25 commented
Prikladám dodatočne prihlasovacie údaje pre 2 typy účtov (dá sa aj zaregistrovať - ako uživateľ):
### Admin:
admin@admin.sk
password
### Uživateľ:
user@user.com
password

2021-06-10 16:26 UTC, nvbach91 requested changes
- nerozumim moc vasi logice pri objednavani, napr. po zadani objednavky zadam dalsi objednavku a tahle uz se nezapise

2021-06-10 16:26 UTC, nvbach91 commented on www/zjaa00/sp-zjaa00/partials/homepage/load_drinks.php
> +		<div
pro AJAX musite vratit JSON a ne HTML

2021-06-10 16:26 UTC, nvbach91 commented on www/zjaa00/sp-zjaa00/partials/homepage/load_drinks.php
> +					$query = "
SQL dotaz ve for cyklu?

2021-06-10 16:26 UTC, nvbach91 commented on www/zjaa00/sp-zjaa00/partials/homepage/order.php
> +  $select = $connect->prepare("SELECT drink_id, name, volume, price FROM drinks WHERE available = 1 ORDER BY name asc;");
vidim same statementy bez zapouzdreni do trid OOP, to je spatne

2021-06-10 16:26 UTC, nvbach91 commented on www/zjaa00/sp-zjaa00/orders.php
> +  <div>
chce to nejakou navigaci

2021-06-14 10:35 UTC, nvbach91 approved these changes

2021-06-14 10:35 UTC, merged