sp-feda07
nvbach91/4IZ278-2020-2021-LS pull request #254
Opened 2021-05-16 18:24 UTC by alexa-dzhan

2021-06-16 07:06 UTC, alexa-dzhan commented
Nemuzu rozbehat na eso.vse.cz Pise to Internal Server Error a zadne upresneni (nevim ani kde hledat chybu).

https://eso.vse.cz/~feda07/sp

2021-06-16 08:21 UTC, nvbach91 commented
https://github.com/nvbach91/4IZ278-2020-2021-LS/issues/273

2021-06-16 15:18 UTC, alexa-dzhan commented
http://sp-feda07.herokuapp.com/home

2021-06-17 15:28 UTC, nvbach91 requested changes
- jak se da odhlasit z aplikace?
- tvorba sluzby - 0 a zaporne hodnoty pro cas
- kdyz jsem prihlaseny tak bych uz nemel videt login/register
- editace profilu - proc je formular prazdny kdyz se otevre?
- jak se da editovat/spravovat jiz vytvorene sluzby?
- proc se u sluzeb zobrazuje avatar?
- proc se lisi vybrane datum pri rezervace od datumu v seznamu rezervaci?
- proc nelze vybrat jiz rezervovane casy v jinych dnech?

2021-06-18 14:16 UTC, nvbach91 approved these changes

2021-06-18 14:17 UTC, merged