bejj01-sp
nvbach91/4IZ278-2020-2021-LS pull request #257
Opened 2021-05-16 20:09 UTC by bejjak

Pilotní verze semestrální práce.

2021-05-16 22:35 UTC, bejjak commented
Momentální verze se základní funkčností z pilotního pushe dostupná na [odkaz](https://sp-4iz278-sport-ticket.herokuapp.com/home)

2021-06-09 13:09 UTC, bejjak commented
Finální verze semestrální práce, měl jsem nějaké problémy s gitem, proto se zpožděním.
Odkaz na aplikaci: https://sp-4iz278-sport-ticket.herokuapp.com/

admin účet: 
     - email: admin@admin.com
     - heslo: adminadmin

2021-06-10 16:06 UTC, nvbach91 requested changes
- slo by osetrit toto?
  - https://sp-4iz278-sport-ticket.herokuapp.com/ticket-detail/0/pdf
  - https://sp-4iz278-sport-ticket.herokuapp.com/ticket-detail/0
- to same u eventu
- dalsi chyba pri zakladani eventu:

![image](https://user-images.githubusercontent.com/20724910/121559642-0f055b80-ca17-11eb-83c8-c6fae477d6ca.png)

![image](https://user-images.githubusercontent.com/20724910/121559616-07de4d80-ca17-11eb-862b-73d506709cd0.png)

![image](https://user-images.githubusercontent.com/20724910/121559511-ed0bd900-ca16-11eb-8a0b-2e3e9583ba5e.png)

2021-06-10 21:47 UTC, bejjak commented
Opravená verze by měla být deploynuta.

2021-06-11 10:34 UTC, bejjak commented
Změny z obhajoby pushnuty a deploynuty.

2021-06-11 10:39 UTC, nvbach91 approved these changes

2021-06-11 10:42 UTC, merged