prepare folder structure
nvbach91/4IZ278-2020-2021-LS pull request #266
Opened 2021-05-17 19:50 UTC by pesa06

2021-05-17 20:11 UTC, pesa06 commented
Navazuji na [PR, ktery jsem zavrel](https://github.com/nvbach91/4IZ278-2020-2021-LS/pull/256)
V prvnich par commitech jsem nahral kod sve semestralni prace na 4IZ110, ze ktere jsem vychazel, potom je tam commit, ve kterem jsem jiz zacal delat zmeny i s popisem, co jsem udelal.
Pokud budete mit zajem, do repozitare, [kde na projektu pracuji](https://github.com/pesa06/sem-project) jsem Vam poslal novou pozvanku.

2021-06-15 20:08 UTC, pesa06 commented
Semestralka je pristupna z internetu [zde](http://pesa06sem.cz/sem-pesa06/www/clanky). Pokud budete chtit, dejte vedet a na email Vam necham vygenerovat heslo pro pristup.

2021-06-17 16:30 UTC, nvbach91 commented
bez prihlaseni tam skoro nic neudelam, neni tam ani registrace, je to schvalne? co jste navic udelal oproti puvodni verzi?

2021-06-17 16:53 UTC, pesa06 commented
Vytvořil jsem Vám nový účet pod emailem nvbach91@outlook.com, přijde Vám na něj heslo. Opravdu je to tak schválně, část bez přihlášení je pouze pro veřejnost - rodiče, hráče apod., veškerá administrace se skrývá za přihlášením a účty můžou generovat pouze uživatelé, kteří mají roli administrátora.
Oproti původní verzi jsem na části přístupné pro veřejnost upravil URL tak, aby byly více přívětivé pro SEO, přidal meta tagy.
Provedl jsem mírné změny v databázi a struktuře aplikace, například zaměstnanec nyní může mít více pozic i ve více týmech (věkových kategoriích).
Celou aplikaci jsem rozdělil na moduly - modul pro veřejnost bez přihlášení a modul pro administraci schovaný za přihlášením.
Přidal jsem vytváření účtů, přihlašování. Také přibyla správa pozic zaměstnanců - předtím byly pouze v enumu, nyní jsou v databázi, tedy jdou vytvářet a editovat.
Přidal jsem generování dokumentů - faktur, žádostí o zaslání příspěvků a jejich následný export do PDF a zaslání na mail. Pokud je to vydaná faktura či žádost o zaplacení příspěvků, PDF obsahuje i QR kód pro online platbu .
Na části pro veřejnost přibyl výpis článků se stránkováním, výpis jednotlivých týmů je pouze copypaste z backendové části s odebráním linků pro editaci jednotlivých dat.

2021-06-17 16:55 UTC, pesa06 commented
[priloha.pdf](https://github.com/nvbach91/4IZ278-2020-2021-LS/files/6671900/priloha.pdf)
Pro ukázku, takto vypadá vygenerované PDF se žádostí o zaplacení příspěvků. Tyto dokumenty jdou generovat buď pro jednoho člena, nebo přímo pro celý tým (věkovou kategorii). Ve formuláři se dá zaškrtnout, zda chceme dokument rovnou poslat adresátovi na email, či pouze vygenerovat.

2021-06-17 16:59 UTC, nvbach91 requested changes
- je potreba osetrit 404 pripady, napr. http://pesa06sem.cz/sem-pesa06/www/backoffice.member/upsert?memberId=1x55, nebbo http://pesa06sem.cz/sem-pesa06/www/backoffice.staff/upsert?staffId=2
- zvyraznete polozku v menu podle aktivni stranky
- zvyraznete povinne pole ve formularich
- pridejte validaci formularu na serveru, napr u editace clena
- pridejte moznost vymazu pozice
- jak prirazujete hrace/zaky k starsim/dorostu a muzum? podle datumu narozeni?

2021-06-17 17:09 UTC, pesa06 commented
Ok, provedu.
Roztrideni do tymu je dle veku, u tymu se zada napriklad se ze jedna o U9, po stisku tlacitka pro rozrazeni do tymu se do neho priradi hraci, kteri v aktualnim roce dosahnou veku 8 nebo 9 let. Takhle se to provede pro vsecny tymy, kteri maji zaskrtnuto, ze jsou mladeznicke, pokud nejaky hrac nema svuj tym a je starsi 15 let, priradi se do tymu dospelych(pokud existuje).

2021-06-18 09:56 UTC, nvbach91 approved these changes

2021-06-18 09:56 UTC, merged