sp-tson00
nvbach91/4IZ278-2020-2021-LS pull request #269
Opened 2021-05-18 11:37 UTC by tson00

2021-06-16 00:37 UTC, tson00 commented
Semestrální práce

2021-06-17 16:11 UTC, nvbach91 requested changes
https://eso.vse.cz/~tson00/sp/

- pridejte moznost klikani na nazvy kategorie, univerzitu i koleje v tabulce
- pridejte odkaz na registraci/login na strance produktu kdyz uzivatel neni prihlaseny
- vybrane filtry nechte vyplnene po vyhledavani
- tlacitko smazat prejmenujte na zrusit filtry
- filtry je lepsi posilat pomoci GET metody, ne POST
- pridejte pravidlo pro bezpecnejsi heslo pri registraci
- pridejte emailovou notifikaci po registraci
- pridejte validaci vstupu pri zakladani zbozi
- nelze pridavat zbozi, dostal jsem `
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'validity' doesn't have a default value in /home/httpd/html/users/tson00/sp/new_product.php:33 Stack trace: #0 /home/httpd/html/users/tson00/sp/new_product.php(33): PDOStatement->execute(Array) #1 {main} thrown in /home/httpd/html/users/tson00/sp/new_product.php on line 33`
- jak je mozne ze mam zapujcenou vickrat fletnu?

![image](https://user-images.githubusercontent.com/20724910/122434346-4e8ff280-cf97-11eb-8d73-57c87b029260.png)
-- jak je mozne ze se porad zobrazuje fletna kdyz uz ji majitel nekomu zapujcil?

2021-06-17 22:05 UTC, tson00 commented
Opraveno a nahráno, snad jsem všechno pochopila správně.

2021-06-18 13:40 UTC, nvbach91 approved these changes

2021-06-18 13:40 UTC, merged