sp-vond07
nvbach91/4IZ278-2020-2021-LS pull request #270
Opened 2021-05-19 13:40 UTC by vond07

Pilotní verze
Odkaz na ESO: https://eso.vse.cz/~vond07/www/vond07/semp/views/index.php

2021-05-26 14:52 UTC, nvbach91 commented on www/vond07/semp/config/config.php
> +const DB_PASSWORD = 'aH4riequoh7aib4yei';
citliva data se nedavaji na Git

2021-05-26 14:53 UTC, nvbach91 commented
na serveru eso mejte svou praci tak aby byla dostupna jako https://eso.vse.cz/~vond07/sp/

2021-06-17 11:09 UTC, vond07 commented
Odkaz na ESO: https://eso.vse.cz/~vond07/www/vond07/sem/server.php

2021-06-17 16:39 UTC, nvbach91 requested changes
- odkazy v aplikaci je divne navrzeny, jestli pouzivate nejaky framework tak je potreba nakonfigurovat presmerovani nebo to nasadit jinak
- dostal jsem chybu po registraci
![image](https://user-images.githubusercontent.com/20724910/122438091-a3813800-cf9a-11eb-90dd-5b1b45fc9ae6.png)
- takhle vypada stranka password reset a tudiz se mi nepodarilo zaregistrovat do aplikace 
![image](https://user-images.githubusercontent.com/20724910/122438267-d4fa0380-cf9a-11eb-9e0d-489f30118838.png)

2021-06-18 15:04 UTC, nvbach91 approved these changes

2021-06-24 08:48 UTC, merged