cv02
nvbach91/4IZ278-2020-2021-LS pull request #64
Opened 2021-02-26 22:49 UTC by guliamar

2021-02-27 12:09 UTC, nvbach91 requested changes
chybi pouziti rozdelovani programu do vice casti pomoci include/require

2021-02-27 12:09 UTC, nvbach91 commented on www/gulm04/cv02-ukazky/cv02/index.php
> +class Bcard {
BusinessCard

2021-02-27 12:09 UTC, nvbach91 commented on www/gulm04/cv02-ukazky/cv02/index.php
> +            <img src='./blacklogo.png' alt=" ">
uvozovky

2021-02-27 12:09 UTC, nvbach91 commented on www/gulm04/cv02-ukazky/cv02/index.php
> +<h1>CV01 - i'm really sorry, but my first PHP-page sucks</h1>
naformatovat

2021-03-03 22:32 UTC, guliamar commented
https://eso.vse.cz/~gulm04/cv02/

2021-03-04 09:56 UTC, nvbach91 approved these changes

2021-03-04 09:56 UTC, merged