blak05-cv03
nvbach91/4IZ278-2020-2021-LS pull request #76
Opened 2021-03-05 18:01 UTC by krystofblak05

https://eso.vse.cz/~blak05/cv03/index.php

2021-03-05 23:12 UTC, nvbach91 requested changes

2021-03-05 23:12 UTC, nvbach91 commented on www/blak05/cv03/index.php
> +            if(!preg_match('/^[0-9]\z/', $numCards)){
nemuzu mit vic jak 9 karet? a muzu prijit bez karet?

2021-03-10 15:03 UTC, krystofblak05 commented on www/blak05/cv03/index.php
> +            if(!preg_match('/^[0-9]\z/', $numCards)){
nahrál jsem v neděli opravenou verzi, je už vše v pořádku? nerad bych přišel o bodík

2021-03-12 11:43 UTC, nvbach91 approved these changes

2021-03-12 11:43 UTC, merged